# 输出一些调试信息
message(STATUS "来自 t1 的输出信息")
message(STATUS "项目名称 PROJECT_NAME: ${PROJECT_NAME}")
message(STATUS "项目全称 CMAKE_PROJECT_NAME: ${CMAKE_PROJECT_NAME}")
message(STATUS "项目语言 PROJECT_LANGUAGES: ${PROJECT_LANGUAGES}")
# VERSION
message(STATUS "版本信息 PROJECT_VERSION: ${PROJECT_VERSION}")
message(STATUS "主要版本 PROJECT_VERSION_MAJOR: ${PROJECT_VERSION_MAJOR}")
message(STATUS "次要版本 PROJECT_VERSION_MINOR: ${PROJECT_VERSION_MINOR}")
message(STATUS "补丁版本 PROJECT_VERSION_PATCH: ${PROJECT_VERSION_PATCH}")
# dir （目录）
message(STATUS "源代码目录 CMAKE_SOURCE_DIR: ${CMAKE_SOURCE_DIR}")
message(STATUS "编译目录 CMAKE_BINARY_DIR: ${CMAKE_BINARY_DIR}")
message(STATUS "项目源目录 PROJECT_SOURCE_DIR: ${PROJECT_SOURCE_DIR}")
message(STATUS "项目编译目录 PROJECT_BINARY_DIR: ${PROJECT_BINARY_DIR}")
message(STATUS "当前源代码目录 CMAKE_CURRENT_SOURCE_DIR: ${CMAKE_CURRENT_SOURCE_DIR}")
message(STATUS "当前编译目录 CMAKE_CURRENT_BINARY_DIR: ${CMAKE_CURRENT_BINARY_DIR}")
# file
message(STATUS "当前脚本完整名称 CMAKE_CURRENT_LIST_FILE: ${CMAKE_CURRENT_LIST_FILE}")
message(STATUS "当前脚本完整目录 CMAKE_CURRENT_LIST_DIR: ${CMAKE_CURRENT_LIST_DIR}")
# 输出当前的 CMAKE_INSTALL_PREFIX
message(STATUS "安装路径 CMAKE_INSTALL_PREFIX: ${CMAKE_INSTALL_PREFIX}")
# 输出当前的 CMAKE_INSTALL_BINDIR
message(STATUS "CMAKE_INSTALL_BINDIR: ${CMAKE_INSTALL_BINDIR}")

